export type AirtableEstimateFields = {
  "id": string;
  "Unique ID": string;
  "Study Design": string;
  "Inclusion Criteria": string;
  "Exclusion Criteria": string;
  Age: string;
  "Age Minimum": number;
  "Age Maximum": number;
  Sex: string;
  "Sample Frame": string;
  "Sample Frame - Target Group": string;
  "Sampling Method": string;
  Pathogen: string;
  Antibody: string[];
  Antigen: string;
  "Source Sheet": string[];
  Producer: string;
  "Producer - Other": string;
  Assay: string;
  "Assay - Other": string;
  "Sample Start Date": `${number}-${number}-${number}`;
  "Sample End Date": `${number}-${number}-${number}`;
  "Sample Size": number;
  Seroprevalence: number;
  "Subgroups Available": string[];
  Continent: string;
  "Country archive": string;
  "Sample Numerator": number;
  URL: string[];
  Country: string;
  "Age group": string;
  City: string;
  State: string;
  "ETL Included": 0 | 1;
  "Publication Date": unknown[];
  "First Author Last Name": unknown[];
  "WHO Region": string[];
} & Record<string, never>;

export type AirtableSourceFields = {
  "id": string;
  "Source Title": string;
  "First Author": string;
  "Publication Date": `${number}-${number}-${number}`;
  URL: string;
  "Unique ID": string[];
  Extractor: string;
  "First Author Last Name": string;
} & Record<string, never>;
