export type AirtableEstimateFields = {
  "id": string;
  "Unique ID": string | undefined;
  "Study Design": string | undefined;
  "Inclusion Criteria": string | undefined;
  "Exclusion Criteria": string | undefined;
  Age: string | undefined;
  "Age Minimum": number | undefined;
  "Age Maximum": number | undefined;
  Sex: string | undefined;
  "Sample Frame": string | undefined;
  "Sample Frame - Target Group": string | undefined;
  "Sampling Method": string | undefined;
  Pathogen: string;
  Antibody: string[] | undefined;
  Antigen: string | undefined;
  "Source Sheet": string[] | undefined;
  "Pediatric age group": string | undefined;
  Producer: string | undefined;
  "Producer - Other": string | undefined;
  Assay: string | undefined;
  "Assay - Other": string | undefined;
  "Sample Start Date": `${number}-${number}-${number}` | undefined;
  "Sample End Date": `${number}-${number}-${number}` | undefined;
  "Sample Size": number | undefined;
  "Serotype": string[] | undefined;
  Seroprevalence: number | undefined;
  "Subgroups Available": string[] | undefined;
  Continent: string | undefined;
  "Country archive": string | undefined;
  "Sample Numerator": number | undefined;
  URL: string[] | undefined;
  Country: string | undefined;
  "Age group": string | undefined;
  City: string | undefined;
  State: string | undefined;
  "ETL Included": 0 | 1 | undefined;
  "Publication Date": unknown[] | undefined;
  "First Author Last Name": unknown[] | undefined;
  "WHO Region": string[] | undefined;
} & Record<string, never>;

export type AirtableSourceFields = {
  "id": string;
  "Source Title": string | undefined;
  "First Author": string | undefined;
  "Publication Date": `${number}-${number}-${number}` | undefined;
  URL: string | undefined;
  "Unique ID": string[] | undefined;
  Extractor: string | undefined;
  "First Author Last Name": string | undefined;
} & Record<string, never>;
